paytm.payment:
  sandbox:
    merchantId: XVAhuN82421525437049
    merchantKey: xomAz9ZfRmCJVCsY
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Retail
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    refundUrl : https://securegw-stage.paytm.in/refund/apply
    refundStatusUrl : https://securegw-stage.paytm.in/v2/refund/status
    callbackUrl: http://localhost:8090/api/0.1/paytm-payment/response
    details:
      MID: ${paytm.payment.sandbox.merchantid}
      CHANNEL_ID: ${paytm.payment.sandbox.channelid}
      INDUSTRY_TYPE_ID: ${paytm.payment.sandbox.industrytypeid}
      WEBSITE: ${paytm.payment.sandbox.website}
      CALLBACK_URL: ${paytm.payment.sandbox.callbackUrl}
